# Generated by Django 5.2.15 on 2026-06-15 00:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_date', models.DateField()),
                ('period', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night')], max_length=20)),
                ('photo_url', models.URLField(max_length=500)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('points_granted', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('shared_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='groups.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'class_date', 'period'), name='unique_attendance_user_class_date_period'), models.CheckConstraint(condition=models.Q(('points_granted__gte', 0)), name='attendance_points_granted_gte_0')],
            },
        ),
    ]
