# Generated by Django 5.2.14 on 2026-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='photo_url',
            field=models.ImageField(upload_to='attendance_photos/'),
        ),
    ]
