# Generated by Django 5.2.15 on 2026-06-15 01:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_streak', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('longest_streak', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_valid_activity_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('current_streak__gte', 0)), name='user_progress_current_streak_gte_0'), models.CheckConstraint(condition=models.Q(('longest_streak__gte', 0)), name='user_progress_longest_streak_gte_0'), models.CheckConstraint(condition=models.Q(('total_points__gte', 0)), name='user_progress_total_points_gte_0'), models.CheckConstraint(condition=models.Q(('longest_streak__gte', models.F('current_streak'))), name='user_progress_longest_gte_current')],
            },
        ),
    ]
